<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <!-- Nâng lên 22621 để khớp với Microsoft.Windows.SDK.Contracts 10.0.22621.2 -->
    <TargetFramework>net8.0-windows10.0.22621.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <!-- Windows.Media.Ocr — built-in OCR engine của Windows, không cần tessdata -->
    <PackageReference Include="Microsoft.Windows.SDK.Contracts" Version="10.0.22621.2" />
    <!-- SkiaSharp để pre-process ảnh -->
    <PackageReference Include="SkiaSharp" Version="2.88.7" />
  </ItemGroup>

</Project>
